### PR TITLE
Fix #36

### LINKED ISSUE #36: Comments break parsing if they are part of normal line
Looks like comments are ignored only if they start the line. In my file I did something like
```
[Some group];some comment
```
and it wasn't parsed correctly as a group.

It should be possible to put comments in regular lines, in which case they should be just trimmed out from the end.

### PR DESCRIPTION
**Pull request by jasonwbarnett**

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
closing due to the inactivity of this project. It appears this whole project is abandoned.

**Comment by derks** [comment]
@jasonwbarnett apologies for lack of response here. I put out a "request for maintainer" over a year ago with no response:

- https://github.com/datafolklabs/ruby-parseconfig/issues/33


I'd like to keep this open, and will make a push to get it merged/released ASAP. Agree, the project is under-maintained but also widely used and not super complex. I really just need one developer who actively uses the library to take it over and keep it alive.

**Review by dmitryshagin — APPROVED** [review]
I've tested it locally and it looks good. Sorry for being a bad maintainer.

**Comment by derks** [comment]
@jasonwbarnett this fix was pushed in the latest deploy to rubygems.org. Thank you for your contribution.

**Pull request merged**
